language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      - secure: PhwjNJQ6bRRY4uh0ILWcp3sjeBOUbf0KUEyrwtRqM7cg4H7XQpkst01eKg0nyymtaJykGO+HwDBTe+4Epszj6aXN0gpT77Adi50KfhODThslMQtZhLBH3mPqPVRvY3H5p1F+B41+mP6i/s3BvCBBq1JviTRncr9RDtltaXh/vbqj1+Y4yRMjKzJzkZAA5BQFm3KbmR8Px2eVd2htM+jS5SzRhH6XlQCdAZXIr5fSicXs6vja8GyNl2lvJ666u2b8PgDXhC3lN9ntpptRWvPvLRcdx0XshAzJnW06r0/HnPaMX09lLu8C4mkIYvdw2zjDsADCvmxD90J3y/8ksYLQr9CDO6Txp1g2KLdKJLigOSu+rq07X79hONPQzvBFMZ/34+cEdnfq6/9fD7hQCNW9tRUHTF5OHSOoSFlpc//du2vAXaqLi+TQ2q50sh0V+KZ1vG1DV+n5U5vxyp4I6828yoLHLw5AC9giP5v1cDbaVCRo1dYUQJeqGwFIn5gCp45eSCrCwtgNTCvVtbjSlmPHI+JD0R+E8GhNjhPV/lZc/Dn3akNbcb2QoKdyOzbbxsH8Rn2MWrjrJaCxUirTHPmUH4hdYLaTLoL1akAA8jje3RbDC9GM3C8XbXGCspiE5tGj2czcutuqJf1IB9Ohi3RPAXNSn4xCHBKtjeEMg9H7gdI=
    on_success: change
    on_failure: always
