name: Test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

env:
  # https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-php-runtimes-8-0-x-and-below-in-the-aws-sdk-for-php/
  AWS_SUPPRESS_PHP_DEPRECATION_WARNING: 1

jobs:

  test_v4:
    runs-on: ${{ matrix.os }}

    env:
      latest_php: 8.3
      latest_laravel: 11

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.1', '8.2', '8.3' ]
        laravel: [ 10, 11 ]
        exclude:
          - php: 8.1
            laravel: 11

    name: v4.x - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: |
            composer require "illuminate/mail=^${{ matrix.laravel }}" --no-update
            composer install --quiet --no-plugins --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Migrate phpunit XML configuration
        run: vendor/bin/phpunit --migrate-configuration || true

      - name: Run test suite
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
        if: matrix.php == env.latest_php && matrix.laravel == env.latest_laravel


  test_v3:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.0', '8.1', '8.2', '8.3' ]
        laravel: [ 9, 10, 11 ]
        exclude:
          - php: 8.0
            laravel: 10
          - php: 8.0
            laravel: 11
          - php: 8.1
            laravel: 11

    name: v3.x - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: v3.x

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: |
            composer require "illuminate/mail=^${{ matrix.laravel }}" --no-update
            composer install --quiet --no-plugins --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Migrate phpunit XML configuration
        run: vendor/bin/phpunit --migrate-configuration || true

      - name: Run test suite
        run: vendor/bin/phpunit


  test_v2:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: ['7.2', '7.3', '7.4', '8.0', '8.1']
        laravel: [ 7, 8 ]
        exclude:
          - php: 7.1
            laravel: 6
          - php: 7.1
            laravel: 7
          - php: 7.1
            laravel: 8
          - php: 7.2
            laravel: 8
          - php: 8.1
            laravel: 6
          - php: 8.1
            laravel: 7

    name: v2.x - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: v2.x

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: |
            composer require "illuminate/mail=^${{ matrix.laravel }}" --no-update
            composer install --quiet --no-plugins --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Run test suite
        run: vendor/bin/phpunit


  test_v1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.1', '7.2', '7.3', '7.4' ]
        laravel: [ 5.7, 5.8, 6 ]
        exclude:
          - php: 7.1
            laravel: 6

    name: v1.x - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: v1.x

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: |
            composer require "illuminate/mail=^${{ matrix.laravel }}" --no-update
            composer install --quiet --no-plugins --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Run test suite
        run: vendor/bin/phpunit
