name: Test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: ['7.2', '7.3', '7.4', '8.0', '8.1']
        laravel: [ 7, 8 ]
        exclude:
          - php: 7.1
            laravel: 6
          - php: 7.1
            laravel: 7
          - php: 7.1
            laravel: 8
          - php: 7.2
            laravel: 8
          - php: 8.1
            laravel: 6
          - php: 8.1
            laravel: 7

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v2.x

      - name: Install dependencies
        run: composer install --quiet --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Run test suite
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
